In [1]:
from sklearn import svm,datasets
iris=datasets.load_iris()

In [6]:
import pandas as pd
df =pd.DataFrame(iris.data,columns=iris.feature_names)
df['flowers']=iris.target
df['flowers']=df['flowers'].apply(lambda x:iris.target_names[x])
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

       flowers  
0       setosa  
1       setosa  
2       setosa  
3       setosa  
4       setosa  
..         ...  
145  virginica  
146  virginica  
147  virginica  
148  virginica  
149  virginica  

[150 rows x 5 columns]

In [35]:
from sklearn.model_selection import train_test_split
import numpy as np
X_train,X_test,Y_train,Y_test=train_test_split(iris.data,iris.target, test_size=0.3)
model=svm.SVC(kernel='rbf',C=30,gamma='auto')
model.fit(X_train,Y_train)
model.score(X_test,Y_test)


0.9555555555555556

In [20]:
from sklearn.model_selection import cross_val_score

In [21]:
cross_val_score(svm.SVC(kernel='linear',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([1.        , 1.        , 0.9       , 0.96666667, 1.        ])

In [22]:
cross_val_score(svm.SVC(kernel='rbf',C=10,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.96666667, 0.96666667, 1.        ])

In [23]:
cross_val_score(svm.SVC(kernel='rbf',C=20,gamma='auto'),iris.data,iris.target,cv=5)

array([0.96666667, 1.        , 0.9       , 0.96666667, 1.        ])

In [25]:
kernel=['rbf','linear']
C=[10,20]
avg_score={}
for ker in kernel:
    for cval in C:
        cv_scores=cross_val_score(svm.SVC(kernel=ker,C=cval,gamma='auto'),iris.data,iris.target,cv=5)
        avg_score[ker + '-' + str(cval)]=np.average(cv_scores)
avg_score    

{'rbf-10': np.float64(0.9800000000000001),
 'rbf-20': np.float64(0.9666666666666668),
 'linear-10': np.float64(0.9733333333333334),
 'linear-20': np.float64(0.9666666666666666)}

In [26]:
# hyper prameter using gridSearchCV
from sklearn.model_selection import GridSearchCV
clf=GridSearchCV(svm.SVC(gamma='auto'),{
    'C':[1,10,20],
    'kernel':['rbf','linear']
},cv=5, return_train_score=False)
clf.fit(iris.data,iris.target)
clf.cv_results_

{'mean_fit_time': array([0.00199866, 0.00119891, 0.00119891, 0.00219908, 0.00159903,
        0.00159945]),
 'std_fit_time': array([5.43678010e-07, 4.00114187e-04, 3.99757239e-04, 3.99637350e-04,
        7.99811893e-04, 4.89706831e-04]),
 'mean_score_time': array([0.0009994 , 0.00100012, 0.0009994 , 0.00199842, 0.00119848,
        0.00059905]),
 'std_score_time': array([5.51978917e-07, 8.97163759e-07, 9.81867804e-07, 6.32183738e-04,
        3.99018132e-04, 4.89122990e-04]),
 'param_C': masked_array(data=[1, 1, 10, 10, 20, 20],
              mask=[False, False, False, False, False, False],
        fill_value=999999),
 'param_kernel': masked_array(data=['rbf', 'linear', 'rbf', 'linear', 'rbf', 'linear'],
              mask=[False, False, False, False, False, False],
        fill_value=np.str_('?'),
             dtype=object),
 'params': [{'C': 1, 'kernel': 'rbf'},
  {'C': 1, 'kernel': 'linear'},
  {'C': 10, 'kernel': 'rbf'},
  {'C': 10, 'kernel': 'linear'},
  {'C': 20, 'kernel': 'rbf'},
 

In [31]:
df=pd.DataFrame(clf.cv_results_)
df

mean_fit_time  std_fit_time  mean_score_time  std_score_time  param_C  \
0       0.001999  5.436780e-07         0.000999    5.519789e-07        1   
1       0.001199  4.001142e-04         0.001000    8.971638e-07        1   
2       0.001199  3.997572e-04         0.000999    9.818678e-07       10   
3       0.002199  3.996374e-04         0.001998    6.321837e-04       10   
4       0.001599  7.998119e-04         0.001198    3.990181e-04       20   
5       0.001599  4.897068e-04         0.000599    4.891230e-04       20   

  param_kernel                         params  split0_test_score  \
0          rbf      {'C': 1, 'kernel': 'rbf'}           0.966667   
1       linear   {'C': 1, 'kernel': 'linear'}           0.966667   
2          rbf     {'C': 10, 'kernel': 'rbf'}           0.966667   
3       linear  {'C': 10, 'kernel': 'linear'}           1.000000   
4          rbf     {'C': 20, 'kernel': 'rbf'}           0.966667   
5       linear  {'C': 20, 'kernel': 'linear'}           1.000000   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0                1.0           0.966667           0.966667                1.0   
1                1.0           0.966667           0.966667                1.0   
2                1.0           0.966667           0.966667                1.0   
3                1.0           0.900000           0.966667                1.0   
4                1.0           0.900000           0.966667                1.0   
5                1.0           0.900000           0.933333                1.0   

   mean_test_score  std_test_score  rank_test_score  
0         0.980000        0.016330                1  
1         0.980000        0.016330                1  
2         0.980000        0.016330                1  
3         0.973333        0.038873                4  
4         0.966667        0.036515                5  
5         0.966667        0.042164                6

In [33]:
df[['param_C','param_kernel','mean_test_score']]

param_C param_kernel  mean_test_score
0        1          rbf         0.980000
1        1       linear         0.980000
2       10          rbf         0.980000
3       10       linear         0.973333
4       20          rbf         0.966667
5       20       linear         0.966667