In [12]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits
digits=load_digits()

In [13]:
X_train,X_test,Y_train,Y_test=train_test_split(digits.data,digits.target, test_size=0.2)

In [14]:
lr=LogisticRegression(max_iter=1000)
lr.fit(X_train,Y_train)
lr.score(X_test,Y_test)

0.9722222222222222

In [15]:
svm=SVC()
svm.fit(X_train,Y_train)
svm.score(X_test,Y_test)

0.9833333333333333

In [16]:
rf= RandomForestClassifier()
rf.fit(X_train,Y_train)
rf.score(X_test,Y_test)

0.9777777777777777

In [20]:
from sklearn.model_selection import KFold
kf= KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [21]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)


[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [22]:
def get_score(model,X_train,X_test,y_train,y_test):
    model.fit(X_train,y_train)
    return model.score(X_test,y_test)

In [25]:
get_score(LogisticRegression(max_iter=1000),X_train,X_test,Y_train,Y_test)

0.9722222222222222

In [26]:
get_score(SVC(),X_train,X_test,Y_train,Y_test)

0.9833333333333333

In [27]:
get_score( RandomForestClassifier(),X_train,X_test,Y_train,Y_test)

0.9694444444444444

In [31]:
from sklearn.model_selection import StratifiedKFold
folds= StratifiedKFold(n_splits=3)

In [43]:
l_score=[]
score_svm=[]
score_rf=[]
for train_index, test_index in kf.split(digits.data):
   x_train,x_test,y_train,y_test= digits.data[train_index],digits.data[test_index],\
                                   digits.target[train_index],digits.target[test_index]
   l_score.append((get_score( RandomForestClassifier(),X_train,X_test,Y_train,Y_test)))
   score_svm.append((get_score( RandomForestClassifier(),X_train,X_test,Y_train,Y_test)))
   score_rf.append((get_score( RandomForestClassifier(),X_train,X_test,Y_train,Y_test)))

In [44]:
l_score

[0.9722222222222222, 0.9722222222222222, 0.9777777777777777]

In [45]:
score_svm

[0.9722222222222222, 0.9666666666666667, 0.9666666666666667]

In [46]:
score_rf

[0.9666666666666667, 0.9777777777777777, 0.975]