In [39]:
#first import the necessary package
import numpy as np
#create the ypred and y true array
ypred=np.array([1,1,0,0,1])
ytrue=np.array([0.30,0.70,1,0,0.5])
#declare a funtion
def mabs(ypred,ytrue):
    totalarr=ypred-ytrue #this compute the diffrence in the two arr
    sumoftotal=np.sum(totalarr) #this sum all the arr
    # then compute the absolute error
    mean_absolute=sumoftotal / len(ytrue)
    print(np.abs(totalarr))
    return mean_absolute
    

In [40]:
mabs(ypred,ytrue)

[0.7 0.3 1.  0.  0.5]


np.float64(0.1)

In [46]:
#mean square error codeblock
#first import the necessary package
import numpy as np
#create the ypred and y true array
ypred=np.array([1,1,0,0,1])
ytrue=np.array([0.30,0.70,1,0,0.5])
emptyarr=[]
result=np.array([])
#declare a funtion
def mse(ypred,ytrue):
    for yprd,ytr in zip(ypred,ytrue):
        squarederr=np.abs(yprd-ytr)
        power=np.power(squarederr,2)
        # print(power)
        emptyarr.append(power)
        result=np.array(emptyarr)
    total=np.sum(result)
    final=total/len(ytrue)
    return final
   

In [47]:
mse(ypred,ytrue)

np.float64(0.366)

In [50]:
# log loss code implementation
# first create an episolon which will avoid you getting value of zero for log
episolon=1e-15

In [51]:
ypred

array([1, 1, 0, 0, 1])

In [54]:
yprd_new=[]
for i in ypred:
    yprd_new.append(max(i,episolon))
yprd_new

[np.int64(1), np.int64(1), 1e-15, 1e-15, np.int64(1)]

In [55]:
y_final=[]
for i in yprd_new:
    y_final.append(min(i,1-episolon))
y_final

[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [56]:
np.log(y_final)

array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [63]:
value1=ytrue*np.log(np.array(y_final)+(1-ytrue))

In [64]:
value1

array([  0.15918848,   0.18365499, -34.53877639,   0.        ,
         0.20273255])

In [65]:
value2=np.log(1 - np.array(y_final))
value2

array([-3.45395760e+01, -3.45395760e+01, -9.99200722e-16, -9.99200722e-16,
       -3.45395760e+01])

In [67]:
-np.mean(value1*value2)

np.float64(3.7687928424840713)